### ISSUE TITLE
Party Overview Not Working - No Popup Displayed When Button is Clicked (dnd5e 4.1.2 → 4.3.3)

### ISSUE THREAD

**Issue by doruBoxShiki** [mclemente/party-overview#91]
I’m Japanese, and this was translated by a machine, so I apologize if it’s difficult to understand.  
I wanted to report that Party Overview has stopped working with the latest version of dnd5e (4.3.3).  

When I press the Party Overview button, a JS error occurs, and the popup doesn’t display.  
It seems to be caused by a change in dnd5e version 4.3.3, where the property `abilities.<ability>.save` was changed to `abilities.<ability>.save.value`.  

Would you be able to fix this when you have some time?  
I wish I could have fixed it myself and submitted a pull request, but... I'm too busy... Sorry about that.  

I’ve included the error code and my environment details below.  
The Japanese FVTT community finds this mod extremely useful, and everyone loves using it!  

Thank you for developing such a great tool!

```js
foundry-esm.js:4621 Error: The 'abilities.<ability>.save' property is now stored in 'abilities.<ability>.save.value'.
Deprecated since Version 4.3
Backwards-compatible support will be removed in Version 4.5
    at Object.logCompatibilityWarning (foundry-esm.js:4609:19)
    at abl.save.toString (common.mjs:167:23)
    at Object.numberFormat (foundry.js:8063:33)
    at Object.c (handlebars.min.js:27:27865)
    at eval (eval at createFunctionContext (handlebars.min.js:29:10011), <anonymous>:11:157)
    at h (handlebars.min.js:27:25975)
    at c (handlebars.min.js:27:6943)
    at handlebars.min.js:27:7576
    at Array.forEach (<anonymous>)
    at handlebars.min.js:27:7544
    at Object.<anonymous> (handlebars.min.js:27:7619)
    at Object.c (handlebars.min.js:27:27865)
    at eval (eval at createFunctionContext (handlebars.min.js:29:10011), <anonymous>:15:49)
    at h (handlebars.min.js:27:25975)
    at c (handlebars.min.js:27:6943)
    at Object.<anonymous> (handlebars.min.js:27:7333)
    at Object.c (handlebars.min.js:27:27865)
    at Object.eval [as main] (eval at createFunctionContext (handlebars.min.js:29:10011), <anonymous>:89:49)
    at c (handlebars.min.js:27:23534)
    at d (handlebars.min.js:27:23849)
    at e (handlebars.min.js:28:30886)
    at renderTemplate (foundry.js:7902:10)
    at async PartyOverviewApp._renderInner (foundry.js:6013:16)
    at async PartyOverviewApp._render (foundry.js:5844:19)

```

**Environment:**  
- Onse Kobo Foundry VTT: Version 12 Stable, 12.331  
- Game System: dnd5e, 4.3.3  
- Enabled Modules: 71  
- Spec Settings: 2  

**OS:**  
- Windows 19.0.0 x86 (64-bit)  
- Client: Not(A:Brand/24.0.0.0  
- GPU: ANGLE (NVIDIA, NVIDIA GeForce GTX 1050 (0x00001C81) Direct3D11 vs_5_0 ps_5_0, D3D11)  
- Maximum Texture Size: 16384  

**Scene:**  
- Resolution: 16583 x 11389  
- Grid Size: 100  
- Map Padding: 0.25  
- Walls: 1140  
- Ambient Lights: 16  
- Ambient Sounds: 0  
- Tiles: 0  
- Tokens: 24  
- Maximum Texture Size: 10983 x 7591.033447265625  

**Entities:**  
- Characters: 191  
- Items: 2  
- Journals: 529  
- Roll Tables: 14  
- Playlists: 5  
- Compendium Packs: 54  
- Chat Messages: 850  

**World Script:**  
- (No specific details provided)  

---

### **Module Information:**  
- **Core Version:** 12.331  
- **System:** dnd5e 4.3.3 (Atropos)  

**Modules:**  
- `advanced-drawing-tools 2.1.1 (dev7355608)`  
- `always-hp 12.01 (IronMonk)`  
- `autoanimations 5.0.1 (theripper93, Otigon (Otigon#2010))`  
- `babele 2.5.6 (Simone)`  
- `bossbar 3.0.6 (theripper93)`  
- `CautiousGamemastersPack 1.9.0 (Alan Davies, Shoyu Vanilla)`  
- `clipboard-image 0.4.0 (Saif Addin Ellafi)`  
- `colorsettings 3.0.3 (ardittristan#0001)`  
- `combat-enhancements 1.2.4 (Asacolips)`  
- `combat-tracker-dock 3.1.6 (theripper93)`  
- `combatbooster 4.0.3 (theripper93)`  
- `comprehend-languages 2.2.3 (Meneltamar)`  
- `dae 12.0.10 (tposney)`  
- `dfreds-convenient-effects 7.1.2 (DFreds)`  
- `dfreds-droppables 4.0.1 (DFreds)`  
- `dice-calculator 2.2.5 (Asacolips, Matheus Clemente)`  
- `dice-so-nice 5.1.4 (JDW, Simone)`  
- `dnd5e-animations 1.7.1 (MrVauxs)`  
- `dnd5eja 26.0.0 (Brother Sharp)`  
- `drag-ruler 1.14.2 (Manuel Vögele)`  
- `dramatic-rolls 3.1.1 (Glen Simon)`  
- `easy-target 3.0 (Kim Mantas)`  
- `enhancedcombathud 3.1.0 (theripper93, Mouse0270)`  
- `enhancedcombathud-dnd5e 4.1.3 (theripper93)`  
- `fateroll 12.0 ()`  
- `forien-copy-environment v2.2.4 (Blair McMillan, Forien)`  
- `forien-quest-log v0.8.1 (Forien, Michael Leahy (TyphonJS))`  
- `foundryVTTja 4.1 (Brother Sharp)`  
- `fvtt-party-resources 1.7.0 (Dave Lens, Kit)`  
- `fxmaster 4.1.0 (Johannes Loher (ghost), Emmanuel Ruaud (U~man))`  
- `illandril-token-tooltips 4.2.0 (Joe Spandrusyszyn (illandril))`  
- `initiative-double-click 1.8 (Matheus Clemente)`  
- `item-piles 3.1.6 (Wasp)`  
- `JB2A_DnD5e 0.7.5 (Jules, Ben)`  
- `lib-wrapper 1.13.2.0 (Rui Pinheiro)`  
- `lmrtfy 3.1.9 (VTT Lair)`  
- `lootsheet-simple 12.400.8 (Jan Ole Peek (ChalkOne))`  
- `metron 0.3.6 (Ethaks)`  
- `midi-qol 12.4.21 (tposney)`  
- `monks-active-tiles 12.02 (IronMonk)`  
- `monks-little-details 12.04 (IronMonk)`  
- `monks-tokenbar 12.04 (IronMonk)`  
- `multi-token-edit 1.79.1 (Aedif)`  
- `multilevel-tokens 1.7.5 (grandseiken, LeRatierBretonnien)`  
- `multiple-document-selection 12.01 (IronMonk)`  
- `party-overview 2.18.2 (Matheus Clemente)`  
- `pin-cushion 12.0.3 (Cole Schultz, Kandashi, ghost, Evan Clarke, Ethaks, p4535992)`  
- `pointers 0.0.6 (Xaukael)`  
- `polyglot 2.4.21 (Matheus Clemente)`  
- `potato-or-not 0.8.0 (Wasp)`  
- `quick-insert 3.2.0 (Sunspots)`  
- `retroactive-advantage-5e 12.0.0 (Andrew Krigline, Zhell)`  
- `roll-from-compendium 1.8.1 (shemetz)`  
- `scaleGrid 1.4.5 (ArcaneRoboBrain, jbhaywood, atomdmac, TheGoodwin)`  
- `sequencer 3.4.7 (Wasp)`  
- `settings-extender 1.2.3 (azzuritetv on Discord)`  
- `share-media 1.1.0 (Maxime)`  
- `simple-chat-tabs 1.1 (Matheus Clemente)`  
- `smarttarget 2.0.0 (theripper93)`  
- `socketlib 1.1.0 (Manuel Vögele)`  
- `splatter 4.0.5 (theripper93)`  
- `tagger 1.5.1 (Wasp)`  
- `tidy-ui_game-settings 0.1.52 (sdenec)`  
- `tile-scroll 3.3 (theripper93)`  
- `token-action-hud 3.0.21 (Larkinabout, Drental, ^ and stick)`  
- `token-action-hud-core 2.0.10 (Larkinabout, Drental, ^ and stick)`  
- `token-action-hud-dnd5e 2.0.2 (Larkinabout, Drental, ^ and stick)`  
- `token-ease 1.3.0 (Wasp, Kerrec Snowmane)`  
- `token-mold 2.22.3 (Moerill, Geekswordsman, BeardedGnome)`  
- `your-turn 1.2.12 (Autmor, EndlessFractal)`  
- `_chatcommands 2.0.2 (Adrian Haberecht)`  

This list was generated using **Forien's Copy Environment**:  
[https://github.com/League-of-Foundry-Developers/foundryvtt-forien-copy-environment](https://github.com/League-of-Foundry-Developers/foundryvtt-forien-copy-environment)

**Comment by doruBoxShiki** [comment]
Sorry, I included unnecessary information.  
Although I listed all the mods, I’ve already tested it with most of them turned off to confirm that it’s not a bug caused by mod interference.

**Comment by ampercival** [comment]
I have the same issue 4.3.5

**Comment by mclemente** [comment]
Fixed by https://github.com/mclemente/party-overview/commit/8d304c38996287b56c2278fc1722491985a658a0
Expect a release with the fix later today.
